import nodemailer from 'nodemailer'
let transporter=nodemailer.createTransport({
    service:'gmail',
    auth:{
        user:"esp.crisisconnect@gmail.com",//your email here
        pass:"ntcx ojuc qvmx zyek"//your app password here (generated by google)
    }
})
export default  transporter