import nodemailer from 'nodemailer'
let transporter=nodemailer.createTransport({
    service:'gmail',
    auth:{
        user:"arpana036@gmail.com",//your email here
        pass:"fvcc xagi vhhb ltuw"//your app password here (generated by google)
    }
})
export default  transporter